Dask tuto
ULHPC/tutorials pull request #25
Opened 2021-09-23 15:03 UTC by ekieffer

* Small tuto on Dask

2021-09-23 17:00 UTC, Falkor requested changes

2021-09-23 17:00 UTC, Falkor commented on python/advanced/dask-ml/scripts/cluster_jobs_workers.py
> +                       queue="batch",
Collect current allocated values from SLURM variables (provide defaults if not set) `os.environ("SLURM[...]"`

2021-09-23 17:00 UTC, Falkor commented on python/advanced/dask-ml/scripts/cluster_jobs_workers.py
> +cluster.scale(5)
Adapt to allocation with reasonable default. Ex:
```suggestion
numworkers = int(os.environ("SLURM_NTASKS")) if os.environ("SLURM_NTASKS") else 1
cluster.scale(numworkers)
```

2021-09-23 17:00 UTC, Falkor commented on python/advanced/dask-ml/scripts/cluster_jobs_workers.sh
> +#SBATCH --cpus-per-task=1
Allow/demo of multi-threaded worker?

2021-09-23 17:00 UTC, Falkor commented on python/advanced/dask-ml/scripts/cluster_steps_workers.sh
> +#SBATCH --ntasks-per-node=4
Comment to suggest maximizing nodes usage (28 tasks on iris, 128 on aion or decrease and increase multithreading. I would suggest --ntasks-per-sockets and link to doc https://hpc-docs.uni.lu/slurm/#specific-resource-allocation

2021-09-23 17:00 UTC, Falkor commented on python/advanced/dask-ml/scripts/launcher_dask.sh
> +#SBATCH --mail-type=BEGIN,FAIL,END
```suggestion
###SBATCH --mail-user=firstname.lastname@uni.lu   # Adapt accordingly
###SBATCH --mail-type=BEGIN,FAIL,END
```

2021-09-23 17:00 UTC, Falkor commented on python/advanced/dask-ml/scripts/cluster_steps_workers.sh
> +dask-scheduler  --scheduler-file "${SCHEDULER_FILE}"  --interface "ib0" &
forked sub-process for the controller? can't you avoid it? Separate logs ?

2021-09-23 17:00 UTC, Falkor commented on python/advanced/dask-ml/scripts/cluster_steps_workers.sh
> +srun --cpu-bind=cores dask-worker  --scheduler-file "${SCHEDULER_FILE}"  --interface "ib0" &
Prepare different output log file per worker? `srun --output ${DASK_LOG_DIR}/dask-%j-workers.out` ?
```suggestion
srun --cpu-bind=cores dask-worker  \
     --label \
     --interface "ib0" \
     --scheduler-file "${SCHEDULER_FILE}"  &
```

2021-09-23 17:00 UTC, Falkor commented on python/advanced/dask-ml/scripts/launcher_dask.sh
> +#SBATCH -c 1               # 1 core per task
```suggestion
### Documentation: https://hpc-docs.uni.lu/slurm/launchers/
#SBATCH -p batch           #batch partition
#SBATCH -J DASK_TESTS     #job name
#SBATCH -N 2
#SBATCH --ntasks-per-node  3      # Adapt to maximize node capacity         
#SBATCH -c 1               # 1 core per task
```

2021-09-23 17:00 UTC, Falkor commented on python/advanced/dask-ml/scripts/launcher_dask.sh
> +dask-scheduler --scheduler-file "./scheduler.json" --interface "ib0" &
As above: forked sub-process for controller seems weird.

2021-09-23 17:00 UTC, Falkor commented on python/advanced/dask-ml/scripts/launcher_dask.sh
> +srun --cpu-bind=cores dask-worker  --scheduler-file "./scheduler.json" --interface "ib0" &
Mutualize / factor code? 
Relative path to scheduler.json is probably not recommended....
```suggestion
srun --cpu-bind=cores dask-worker  \
     --label \
     --interface "ib0" \
     --scheduler-file "./scheduler.json"  &
```

2021-09-23 17:00 UTC, Falkor commented on python/advanced/dask-ml/README.md
> +ssh -p 8022 [user]@access-[aion,iris].uni.lu # OR simply ssh [aion,iris]-cluster if configured
```suggestion
# See https://hpc-docs.uni.lu/connect/ssh/
ssh [aion,iris]-cluster    # assuming proper configuration
```

2021-09-23 17:00 UTC, Falkor commented on python/advanced/dask-ml/README.md
> +- Using SLURMCluster class
```suggestion
- Using [`SLURMCluster` class](https://jobqueue.dask.org/en/latest/generated/dask_jobqueue.SLURMCluster.html)
```

2021-09-23 17:00 UTC, Falkor commented on python/advanced/dask-ml/README.md
> +
Suggested (cannot be done since conflict with markdown 

--------------------
## Pre-requisites ##

Ensure you are able to [connect to the UL HPC clusters](https://hpc-docs.uni.lu/connect/ssh/).
In particular, recall that the `module` command **is not** available on the access frontends.

Now you'll need to pull the latest changes in your working copy of the [ULHPC/tutorials](https://github.com/ULHPC/tutorials) you should have cloned in `~/git/github.com/ULHPC/tutorials` (see ["preliminaries" tutorial](../../../preliminaries/))

``` bash
(access)$> cd ~/git/github.com/ULHPC/tutorials
(access)$> git pull
```

Now **configure a dedicated directory `~/tutorials/dask-ml` for this session**

``` bash
# return to your home
(access)$> mkdir -p ~/tutorials/dask-ml
(access)$> cd ~/tutorials/dask-ml
# create a symbolic link to the reference material
(access)$> ln -s ~/git/github.com/ULHPC/tutorials/python/advanced/dask-ml ref.d
```

2021-09-23 17:00 UTC, Falkor commented on python/advanced/dask-ml/README.md
> +cd tutorials/python/advanced/dask-ml/scripts
```suggestion
# Assuming preliminaries done
cd ~/tutorials/dask-ml
ln -s ref.d/scripts scripts
cd scripts
```

2021-09-23 17:00 UTC, Falkor commented on python/advanced/dask-ml/README.md
> +We first create a generic launcher `cluster_jobs_workers.sh`. Be carefull, you will need to install two different virtualenv if you planned to run the code on both clusters, i.e., Aion and Iris.
Why not creating a virtual env named `dask_env_${ULHPC_CLUSTER}` ?

2021-09-23 17:00 UTC, Falkor commented on python/advanced/dask-ml/README.md
> +                       interface="ib0")
See comments on launcher: collect values from SLURM variables

2021-09-23 17:00 UTC, Falkor commented on python/advanced/dask-ml/README.md
> +dask-scheduler  --scheduler-file "${SCHEDULER_FILE}"  --interface "ib0" &
See comments launchers

2021-09-23 17:00 UTC, Falkor commented on python/advanced/dask-ml/README.md
> +srun --cpu-bind=cores dask-worker  --scheduler-file "${SCHEDULER_FILE}"  --interface "ib0" &
See comments launchers

2021-09-23 17:00 UTC, Falkor commented on python/advanced/dask-ml/README.md
> +python -u $*
no `srun [...]` to have a step ?

2021-10-25 08:48 UTC, ekieffer commented on python/advanced/dask-ml/README.md
> +
ok done

2021-10-25 13:56 UTC, merged

2021-10-25 22:08 UTC, Falkor commented
Not all comment resolved before the merge, Ex: current allocated values from SLURM variables.

2021-10-26 15:50 UTC, ekieffer commented on python/advanced/dask-ml/scripts/cluster_steps_workers.sh
> +#SBATCH --ntasks-per-node=4
Added to the tuto to explain that resources should be maximized.

2021-10-26 15:51 UTC, ekieffer commented on python/advanced/dask-ml/README.md
> +python -u $*
Fixed on Ipyparallel to test . Will apply it also here